name: Github Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "1 1 * 1 *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: [ "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: X
          plugin_people: yes
          plugin_people_types: followers, contributors, stargazers, watchers, sponsors, watchers
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          base: repositories
          plugin_traffic: yes
        